module.exports = {
  projects: [
    '<rootDir>/apps/paper-kiosk',
    '<rootDir>/apps/paper-bureau',
    '<rootDir>/apps/paper-editor',
    '<rootDir>/libs/server-commons',
    '<rootDir>/libs/server-database',
    '<rootDir>/libs/shared-commons',
    '<rootDir>/libs/server-repository',
    '<rootDir>/libs/server-editor-service',
    '<rootDir>/libs/server-paper-service',
    '<rootDir>/libs/server-image-service',
    '<rootDir>/libs/server-image-upload',
    '<rootDir>/libs/server-image-commons',
    '<rootDir>/libs/server-authentication',
    '<rootDir>/libs/shared-entities',
    '<rootDir>/libs/ui-commons',
    '<rootDir>/libs/ui-components',
    '<rootDir>/libs/ui-store-editor',
    '<rootDir>/libs/ui-editor-backend',
  ],
};
